### ISSUE TITLE
Tests are regularly timing out

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws-infra#77]
The tests for this repo are regularly timing out:

```
...
[ ejs/aws-infra/examples/fargate ] Still running command '/home/travis/.pulumi/bin/pulumi preview --non-interactive --diff' (/tmp/containers-fargate-7e9da657-482048758)...
The job exceeded the maximum time limit for jobs, and has been terminated.
```

For instance, see https://travis-ci.com/pulumi/pulumi-aws-infra/builds/94905751.

**Comment by CyrusNajmabadi** [comment]
I'm closing this out.  awsinfra has been working fine for many days now.  We looked into this to see if there were any logs or other information that could lead us to undertand what was going on and we couldn't find anything.  If we run into this again, we can see what coudl be done to track this down.
