### ISSUE TITLE
Generally hard to use awsinfra ECS abstractions with existing VPC/subnet/SG

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws-infra#86]
It feels surprisingly hard to use `new awsinfra.ecs.FargateService` with an existing VPC/subnet/SG.

Below is what I ended up with:

```typescript
const metabaseVpc = awsinfra.ec2.Vpc.fromExistingIds("network", {
    vpcId: "vpc-3567864c",
    publicSubnetIds: ["subnet-53f5b81b", "subnet-469cb120"],
}, { providers: { aws: awsProvider } });

const metabaseSecurityGroup = new awsinfra.ec2.SecurityGroup("metabase", {
    instance: aws.ec2.SecurityGroup.get("metabase", "sg-085f945afdff0ba8b", {}, { provider: awsProvider }),
}, { providers: { aws: awsProvider } });

const metabaseCluster = new awsinfra.ecs.Cluster("metabase", {
    vpc: metabaseVpc,
    securityGroups: [metabaseSecurityGroup],
}, { providers: { aws: awsProvider } });

const metabaseService = new awsinfra.ecs.FargateService("metabase", {
    cluster: metabaseCluster,
    assignPublicIp: true,
    taskDefinitionArgs: {
        containers: {
            metabase: {
                image: "metabase/metabase",
                portMappings: [{ containerPort: 3000 }],
                environment: [{ name: "JAVA_TIMEZONE", value: "US/Pacific" }],
                logConfiguration: {
                    logDriver: "awslogs",
                    options: {
                        "awslogs-group": "/ecs/metabase",
                        "awslogs-region": region,
                        "awslogs-stream-prefix": "ecs",
                    },
                },
            },
        },
    },
}, ({ providers: { aws: awsProvider } } as any));
```

Several issues:
1. Duplicate URN issues when using existing subnets
2. Wasn't immediately clear why I need to configure a new Vpc object (or Security GRoup) here - I just wanted to pass `networkConfiguration` directly to `new Service`, which feels like it woud have been easier with the raw `aws.ecs.Service`.
3. I'm still getting `Error: invocation of aws:ec2/getVpc:getVpc returned an error: transport is closing` - not clear if that is due to a bug in the library or something I'm not doing right yet
4. It would be nice to accept strings as input for securityGroups in place of the strongly typed wrappers over security groups - the code above to get an `aws.x.ecs.SecurityGroup` from a string is pretty awkward.

**Comment by lukehoban** [comment]
> Note: the value in these rich objects isn't super apparent here. But it does become nicer if someone else later on needs to come along and do something like .createEgressRule or .openPorts because they want to open up the security rules a bit for their needs.

The scenario here is that the security group and/or subnets were created by someone else, and I'm just wanting to use them to deploy something. I think that will be reasonably common where these are carried across from some other stack or shared network.  The recent changes here seem to have made that use case relatively more painful - if we could either (a) allow passing raw strings instead of these strongly typed objects or (b) make it really easy to construct one of these rich wrappers over an id.

**Comment by CyrusNajmabadi** [comment]
> if we could either (a) allow passing raw strings instead of these strongly typed objects or (b) make it really easy to construct one of these rich wrappers over an id.

Or potentially both (though i worry about the complexity of type-signatures).   I'm working on 'b' now.  my hope is htat you take hte 'small pain' once of just making the rich object, but then you can trivially pass that around as necessary.  Let's try that out and see if it makes things palatable enough.  If not, we can work toward making things even simpler.

**Comment by lukehoban** [comment]
This was fixed as part of follow-on work.
